### ISSUE TITLE
[Fix] 타이머 이슈 해결

### ISSUE THREAD

**Issue by yeahh315** [Link-MIND/TOASTER-iOS#102]
## 👀 이슈 (issue)
타이머 이슈 해결

## 🚀 to-do
- [x] 전체 카테고리 선택 시 불러오기
- [x] 타이머 수정 시 데이트 피커 불러오기
- [x] 타이머 알림 분기처리 로직 수정
