### ISSUE TITLE
[Fix] 셀프 QA 로직 수정

### ISSUE THREAD

**Issue by yeahh315** [Link-MIND/TOASTER-iOS#119]
## 👀 이슈 (issue)
셀프 QA 로직 수정

## 🚀 to-do
- [x] 1:1 문의 연결
- [x] 설정 페이지 알림 API 부착
- [x] 검색 링크 클릭 시 웹뷰
- [x] 검색 카테고리 클릭 시 세부 클립
- [x] 검색 돌아갈 때 Empty UI 사라지도록
