### ISSUE TITLE
[Fix] 1차 QA 반영

### ISSUE THREAD

**Issue by mcrkgus** [Link-MIND/TOASTER-iOS#131]
## 👀 이슈 (issue)

- QA 반영

## 🚀 to-do

- [x] ProgressView 마진 값
- [x] ProgressView Tint Color
- [x] Home View - 00님의 링크 
- [x] AddLink - textfield x 버튼 마진 
- [x] Clip, Timer - 전체 클립 텍스트 변경
