### ISSUE TITLE
[Fix] 1차 QA 반영

### ISSUE THREAD

**Issue by yeahh315** [Link-MIND/TOASTER-iOS#132]
## 👀 이슈 (issue)
1차 QA 반영

## 🚀 to-do
- [x] 검색결과 뷰에서 카테고리 아이콘 및 링크 썸네일 안뜸
- [x] 마이페이지 공사중 이미지
- [x] 바텀시트 타이틀 좌측정렬
- [x] 타이머 반복설정 선택 항목 텍스트 스타일 미적용
- [x] 타이머 추가에서 클립명, 반복주기 텍스트 스타일
- [x] 링크 저장에서 클립 추가 16개 선택시, 토스트 메시지 추가하기 
- [x] 네비 아이콘 수정
