### ISSUE TITLE
[Chore] 검색, 타이머 뷰 디테일 수정

### ISSUE THREAD

**Issue by yeahh315** [Link-MIND/TOASTER-iOS#137]
## 👀 이슈 (issue)
검색, 타이머 뷰 디테일 수정

## 🚀 to-do
- [x] 검색 뷰 디테일 수정 
- [x] 타이머 뷰 디테일 수정
- [x] 클립 선택 수정
