### ISSUE TITLE
[Chore] 2차 QA 반영 

### ISSUE THREAD

**Issue by mcrkgus** [Link-MIND/TOASTER-iOS#156]
## 👀 이슈 (issue)

- 클립 Cell 의 width, height 수정 
- Home화면 2, 3번째 Cell 디바이더 길이 안 맞음 
- Home 화면 프로그레스바 정렬 
- 클립 아이콘 통일

## 🚀 to-do

- [x] width, height 수정 
- [x] Header, Footer 사이즈 수정
- [x] 디바이더 width 수정
- [x] 프로그레스바
- [x] TabBar, Main - 클립 아이콘 통일
