### ISSUE TITLE
[Fix] 3차 QA 반영

### ISSUE THREAD

**Issue by mini-min** [Link-MIND/TOASTER-iOS#158]
## 👀 이슈 (issue)

3차 QA 올라온 것들 반영해봅니다.

## 🚀 to-do

- [x] 개별 링크 웹뷰 > 하단 [사파리 아이콘] 나머지 아이콘들과 높이 정렬 안맞는 것 같아서 확인 부탁드랴요
- [x] 메인뷰 서치바 & 클립뷰 서치바 컴포넌트 크기가 동일하지 않음
- [x] 영문으로 검색시, 링크/클립 제목과 검색 키워드의 대소문자가 다를 경우, 검색 결과에는 반영되나 볼드 처리가 안되어있음 (ex. DO SOPT 링크를 do sopt로 검색시, 볼드 처리 안됨)
