### ISSUE TITLE
[Chore] 단순 코드 관련 멘토님 피드백 반영

### ISSUE THREAD

**Issue by mini-min** [Link-MIND/TOASTER-iOS#175]
## 👀 이슈 (issue)

코드 사용에 대한 멘토님의 피드백 내용을 반영합니다

## 🚀 to-do

- [x] `DispatchQueue.main` 코드 `@MainActor`로 수정
- [x] guard let, if let 간소화
- [x] 접근 제어자 처리 확인
- [x] 고차함수 활용
