### ISSUE TITLE
[Feat] Sheet UISheetPresentationController로 로직 변경

### ISSUE THREAD

**Issue by mini-min** [Link-MIND/TOASTER-iOS#193]
## 👀 이슈 (issue)

UISheetPresentationController를 사용한 바텀시트로 코드를 수정합니다.   
[참고 블로그 글 - UISheetPresentationController를 사용해서 바텀시트(Sheets)를 만들어보자](https://mini-min-dev.tistory.com/294)

## 🚀 to-do

- [x] 클립 - 클립 추가
- [x] 클립 편집 - 클립 이름 수정
- [x] 세부 클립 - 링크 수정하기 & 링크 제목 편집 이중
- [x] 링크 저장 - 클립 추가
- [x] 타이머 - 알림이 꺼져있어요
- [x] 타이머 - 타이머 수정
- [x] 타이머 설정 - 반복설정
