### ISSUE TITLE
[Feat] 웹뷰 네비바 링크 주소 복사 기능 구현 & 툴바 아이콘 변경

### ISSUE THREAD

**Issue by mini-min** [Link-MIND/TOASTER-iOS#208]
## 👀 이슈 (issue)

3차 스프린트 웹뷰 네비바와 툴바 변경 사항 반영합니다.

## 🚀 to-do

- [x] 네비바 링크 복사
- [ ] 툴바 공유 아이콘
- [ ] 툴바 링크 열람 버튼 변경
