### ISSUE TITLE
[Fix] 복사 붙여넣기 허용 알럿 관련 버그 수정

### ISSUE THREAD

**Issue by mini-min** [Link-MIND/TOASTER-iOS#229]
## 🚀 to-do

- [x] 허용 안함 클릭한 뒤, x 아이콘 눌러서 직접 저장하려고 하면 ‘붙여넣기’ 안되는지
- [x] 허용함 클릭해서 저장한 뒤, 다시 동일 링크를 x 아이콘으로 직접 저장하려고 하면 ‘붙여넣기’가 안뜨는지
- [x] 저장 뷰 넘어왔을 때 바로 버튼 활성화
