### ISSUE TITLE
[Feat] 타이머 뷰 UI 구현

### ISSUE THREAD

**Issue by yeahh315** [Link-MIND/TOASTER-iOS#42]
## 👀 이슈 (issue)
타이머 뷰 UI 구현

## 🚀 to-do

- [ ] 알림 분기 처리
- [ ] Empty 분기 처리
- [ ] 메인 타이머 뷰 구현
- [ ] 타이머 수정 및 삭제
- [ ] 클립 선택 뷰 구현
- [ ] 반복 설정 뷰 구현
