### ISSUE TITLE
[Feat] 링크 저장 구현 - 링크 임베드 및 URL 유효 검사 

### ISSUE THREAD

**Issue by mcrkgus** [Link-MIND/TOASTER-iOS#56]
## 👀 이슈 (issue)

- 링크 저장 기능 구현

## 🚀 to-do

- [x] TextField 타이머 설정 후 일정 시간 초과 시 Error
- [x] TextField 올바른 링크 판단 후 Error 
- [x] 2가지 경우의 Error 발생 시 분기 처리 
- [ ] URL 유효 검사 - 정규식
