### ISSUE TITLE
[Chore] 클립뷰 관련 디자인 변경사항 반영

### ISSUE THREAD

**Issue by mini-min** [Link-MIND/TOASTER-iOS#61]
## 👀 이슈 (issue)

제가 담당하는 클립, 클립 편집 화면에서 기능이나, 디자인으로 바뀐 사항을 반영하겠습니다.

## 🚀 to-do

- [x] SearchVC 검색바 클릭시 연결
- [x] 링크 셀에서 열람, 미열람 구분 방식 추가
- [x] 열람 취소 토스트 팝업 추가
- [x] 바텀시트 경고 메시지 표출 방법 구현 (토스트 팝업 or 동적 높이 조절)
