### ISSUE TITLE
[Feat] 클립뷰 네트워크 연결

### ISSUE THREAD

**Issue by mini-min** [Link-MIND/TOASTER-iOS#63]
## 👀 이슈 (issue)

클립뷰

## 🚀 to-do

- [x] GET - 전체 카테고리 조회
- [x] POST - 카테고리 추가
- [x] GET - 카테고리 중복체크
